[General]

Background="Backgrounds/wallpaper.jpg"
DimBackgroundImage="0.0"
ScaleImageCropped="true"
ScreenWidth="1920"
ScreenHeight="1080"

## [Blur Settings]

FullBlur="false"
PartialBlur="false"
BlurRadius="0"

## [Design Customizations]

HaveFormBackground="false"
FormPosition="center"
BackgroundImageHAlignment="center"
BackgroundImageVAlignment="center"
MainColor="#cdd6f4"
AccentColor="#cba6f7"
BackgroundColor="#1e1e2e"
OverrideLoginButtonTextColor="#1e1e2e"
InterfaceShadowSize="4"
InterfaceShadowOpacity="0.5"
RoundCorners="12"
ScreenPadding="0"
Font="JetBrainsMono Nerd Font"
FontSize=""

## [Interface Behavior]

ForceRightToLeft="false"
ForceLastUser="true"
ForcePasswordFocus="true"
ForceHideCompletePassword="false"
ForceHideVirtualKeyboardButton="true"
ForceHideSystemButtons="false"
AllowEmptyPassword="false"
AllowBadUsernames="false"

## [Locale Settings]

Locale=""
HourFormat="HH:mm"
DateFormat="dddd, MMMM d"

## [Translations]

HeaderText=""
TranslatePlaceholderUsername=""
TranslatePlaceholderPassword=""
TranslateShowPassword=""
TranslateLogin=""
TranslateLoginFailedWarning=""
TranslateCapslockWarning=""
TranslateSession=""
TranslateSuspend=""
TranslateHibernate=""
TranslateReboot=""
TranslateShutdown=""
TranslateVirtualKeyboardButton=""
